// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export enum AppSettingKey {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AppSettingLaunchAtLogin = "launchAtLogin",
    AppSettingCloseToTray = "closeToTray",
    AppSettingNotifications = "notifications",
    AppSettingAutoUpdate = "autoUpdate",
};

export interface AppSettings {
    "launchAtLogin": boolean;
    "closeToTray": boolean;
    "notifications": boolean;
    "autoUpdate": boolean;
    "theme": domain$0.Theme;
    "language": domain$0.Language;
}

/**
 * AppSnapshot deliberately mirrors frontend/src/lib/contracts.ts. Upstream
 * Tailscale types must not cross this boundary.
 */
export interface AppSnapshot {
    "source": SnapshotSource;
    "fallbackReason"?: string;
    "runtime": RuntimeState;
    "localDevice": LocalDevice;
    "devices": PeerDevice[] | null;
    "endpoints": Endpoint[] | null;
    "profiles": LoginProfile[] | null;
    "activeEndpointId": string | null;
    "activeProfileId": string | null;
    "preferences": QuickPreferences;
    "settings": AppSettings;
    "diagnostics": Diagnostics;
    "engine": EngineStatus;
    "updatedAt": string;
}

export enum ConnectionType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConnectionTypeDirect = "direct",
    ConnectionTypeRelay = "relay",
    ConnectionTypeOffline = "offline",
};

export interface Diagnostics {
    "appVersion": string;
    "wailsVersion": string;
    "daemonVersion": string;
    "localApi": string;
    "platform": string;
}

export interface Endpoint {
    "id": string;
    "name": string;
    "url": string;
    "kind": EndpointKind;
    "status": EndpointStatus;
    "customCa": boolean;
    "builtIn": boolean;
}

export interface EndpointInput {
    "id"?: string;
    "name": string;
    "url": string;
    "kind": EndpointKind;
    "customCa": boolean;
}

export enum EndpointKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EndpointKindHeadscale = "headscale",
    EndpointKindTailscale = "tailscale",
    EndpointKindCompatible = "compatible",
};

export enum EndpointStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EndpointStatusReachable = "reachable",
    EndpointStatusUnreachable = "unreachable",
    EndpointStatusUnchecked = "unchecked",
};

export interface EngineStatus {
    "ownership": domain$0.EngineOwnership;
    "service": domain$0.EngineServiceState;
    "bundledVersion": string;
    "payloadAvailable": boolean;
    "canInstall": boolean;
    "canStart": boolean;
}

export interface LocalDevice {
    "id": string;
    "name": string;
    "dnsName": string;
    "os": string;
    "addresses": string[] | null;
    "clientVersion": string;
    "connectionType": ConnectionType;
    "relayRegion"?: string;
}

export interface LoginFinishedEvent {
    "sequence": number;
    "sessionId": string;
    "snapshot": AppSnapshot;
}

export interface LoginProfile {
    "id": string;
    "endpointId": string;
    "account": string;
    "displayName": string;
    "active": boolean;
    "state": ProfileState;
    "lastUsedAt": string;
}

export interface LoginResult {
    "endpointId": string;
    "authUrl": string;
}

export interface LoginURLEvent {
    "sequence": number;
    "sessionId": string;
    "endpointId"?: string;
    "url": string;
}

export interface OperationFailedEvent {
    "sequence": number;
    "operation": string;
    "problem": domain$0.Problem;
}

export interface PeerDevice {
    "id": string;
    "name": string;
    "dnsName": string;
    "owner": string;
    "os": string;
    "addresses": string[] | null;
    "online": boolean;
    "lastSeen": string;
    "latencyMs"?: number | null;
    "connectionType": ConnectionType;
    "relayRegion"?: string;
    "exitNodeOption": boolean;
    "tags": string[] | null;
}

export enum PreferenceKey {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PreferenceAcceptDNS = "acceptDns",
    PreferenceAcceptRoutes = "acceptRoutes",
    PreferenceAllowLANAccess = "allowLanAccess",
    PreferenceShieldsUp = "shieldsUp",
};

export enum ProfileState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileStateReady = "ready",
    ProfileStateLoginRequired = "login-required",
    ProfileStateApprovalRequired = "approval-required",
};

export interface QuickPreferences {
    "exitNodeId": string | null;
    "acceptDns": boolean;
    "acceptRoutes": boolean;
    "allowLanAccess": boolean;
    "shieldsUp": boolean;
}

export interface RuntimeState {
    "daemon": domain$0.DaemonState;
    "session": domain$0.SessionState;
    "connection": domain$0.ConnectionState;
    "control": domain$0.ControlState;
}

export interface SnapshotChangedEvent {
    "sequence": number;
    "snapshot": AppSnapshot;
}

export enum SnapshotSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SnapshotSourceNative = "native",
    SnapshotSourceDemo = "demo",
};
