// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backend is the intentionally narrow Wails binding surface. Lifecycle and
 * orchestration stay on the internal application service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tailscale$0 from "../tailscale/models.js";

export function BeginLogin(endpointID: string): $CancellablePromise<application$0.LoginResult> {
    return $Call.ByID(542405194, endpointID);
}

export function DeleteEndpoint(endpointID: string): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(491524582, endpointID);
}

export function EnsureDaemon(): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(1978684442);
}

export function GetSnapshot(): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(1773737680);
}

export function Logout(): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(1675457438);
}

export function PingDevice(deviceID: string): $CancellablePromise<tailscale$0.PingResult> {
    return $Call.ByID(3511441594, deviceID);
}

export function SaveEndpoint(input: application$0.EndpointInput): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(3266011660, input);
}

export function SetAppSetting(key: application$0.AppSettingKey, value: boolean): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(1803722361, key, value);
}

export function SetConnection(enabled: boolean): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(1571076080, enabled);
}

export function SetExitNode(deviceID: string | null): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(291691604, deviceID);
}

export function SetLanguage(language: domain$0.Language): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(1199885474, language);
}

export function SetPreference(key: application$0.PreferenceKey, value: boolean): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(725540533, key, value);
}

export function SetTheme(theme: domain$0.Theme): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(4276977389, theme);
}

export function SwitchProfile(profileID: string): $CancellablePromise<application$0.AppSnapshot> {
    return $Call.ByID(1705768497, profileID);
}
