// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface NavigateEvent {
    "view": NavigationTarget;
}

export enum NavigationTarget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NavigateOverview = "overview",
    NavigateDevices = "devices",
    NavigateNetworks = "networks",
    NavigateSettings = "settings",
};
