// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionState describes the data-plane lifecycle.
 */
export enum ConnectionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConnectionStopped = "stopped",
    ConnectionStarting = "starting",
    ConnectionRunning = "running",
    ConnectionStopping = "stopping",
    ConnectionDegraded = "degraded",
};

/**
 * ControlState describes control-plane reachability. It does not imply that
 * an already established peer tunnel is down.
 */
export enum ControlState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ControlUnknown = "unknown",
    ControlReachable = "reachable",
    ControlUnreachable = "unreachable",
};

/**
 * DaemonState describes whether the local tailscaled service can be used.
 */
export enum DaemonState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DaemonUnknown = "unknown",
    DaemonMissing = "missing",
    DaemonStopped = "stopped",
    DaemonReady = "ready",
    DaemonUnauthorized = "unauthorized",
    DaemonIncompatible = "incompatible",
};

export enum EngineOwnership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EngineOwnershipUnknown = "unknown",
    EngineOwnershipManaged = "managed",
    EngineOwnershipExternal = "external",
    EngineOwnershipPrepared = "prepared",
    EngineOwnershipMissing = "missing",
};

export enum EngineServiceState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EngineServiceUnknown = "unknown",
    EngineServiceMissing = "missing",
    EngineServiceStopped = "stopped",
    EngineServiceStarting = "starting",
    EngineServiceRunning = "running",
    EngineServiceStopping = "stopping",
};

export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorInvalidArgument = "invalid-argument",
    ErrorNotFound = "not-found",
    ErrorConflict = "conflict",
    ErrorPreconditionFailed = "precondition-failed",
    ErrorPermissionDenied = "permission-denied",
    ErrorUnsupported = "unsupported",
    ErrorCancelled = "cancelled",
    ErrorTimeout = "timeout",
    ErrorDaemonMissing = "daemon-missing",
    ErrorDaemonStopped = "daemon-stopped",
    ErrorDaemonUnauthorized = "daemon-unauthorized",
    ErrorDaemonIncompatible = "daemon-incompatible",
    ErrorDaemonUnavailable = "daemon-unavailable",
    ErrorControlUnavailable = "control-unavailable",
    ErrorConfigurationInvalid = "configuration-invalid",
    ErrorConfigurationReadFailed = "configuration-read-failed",
    ErrorConfigurationWriteFailed = "configuration-write-failed",
    ErrorConfigurationUnsupported = "configuration-schema-unsupported",
    ErrorInternal = "internal",
};

export enum Language {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LanguageChinese = "zh-CN",
    LanguageEnglish = "en-US",
};

/**
 * Problem is safe to serialize across the frontend boundary. Detail must not
 * contain stack traces, auth material, or raw secret-bearing payloads.
 */
export interface Problem {
    "code": ErrorCode;
    "message": string;
    "detail"?: string;
    "retryable": boolean;
}

/**
 * SessionState describes authentication independently from tunnel state.
 */
export enum SessionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionNone = "none",
    SessionLoginRequired = "login-required",
    SessionApprovalRequired = "approval-required",
    SessionAuthenticated = "authenticated",
};

export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeSystem = "system",
    ThemeLight = "light",
    ThemeDark = "dark",
};
