// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as application$0 from "../../../../headscaleclient/headscaleclient/internal/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as desktop$0 from "../../../../headscaleclient/headscaleclient/internal/desktop/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:login-finished": application$0.LoginFinishedEvent;
            "app:login-url": application$0.LoginURLEvent;
            "app:navigate": desktop$0.NavigateEvent;
            "app:operation-failed": application$0.OperationFailedEvent;
            "app:snapshot-changed": application$0.SnapshotChangedEvent;
        }
    }
}
