// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PingResult {
    "deviceId": string;
    "latencyMs": number;
    "via": string;
    "relayRegion"?: string;
    "endpoint"?: string;
}
